FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN apt update && apt install -y \
    ffmpeg \
    git \
    curl \
    openssh-client \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt update \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb

WORKDIR /workspace

CMD ["sleep", "infinity"]

