FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN apt update && apt install -y \
    ffmpeg \
    git \
    curl \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["sleep", "infinity"]

